#pragma once

// From glfw3.h
#define FURY_MOUSE_BUTTON_1         0
#define FURY_MOUSE_BUTTON_2         1
#define FURY_MOUSE_BUTTON_3         2
#define FURY_MOUSE_BUTTON_4         3
#define FURY_MOUSE_BUTTON_5         4
#define FURY_MOUSE_BUTTON_6         5
#define FURY_MOUSE_BUTTON_7         6
#define FURY_MOUSE_BUTTON_8         7
#define FURY_MOUSE_BUTTON_LAST      FURY_MOUSE_BUTTON_8
#define FURY_MOUSE_BUTTON_LEFT      FURY_MOUSE_BUTTON_1
#define FURY_MOUSE_BUTTON_RIGHT     FURY_MOUSE_BUTTON_2
#define FURY_MOUSE_BUTTON_MIDDLE    FURY_MOUSE_BUTTON_3

